version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - ./server/.env
    restart: unless-stopped
